services:
  auth-service:
    build: ./auth-service
    ports:
      - "5001:5000"
    env_file: .env
    depends_on: []
    networks:
      - micro-net

  user-service:
    build: ./user-service
    ports:
      - "5002:5000"
    env_file: .env
    depends_on: []
    networks:
      - micro-net

  frontend:
    build: ./frontend
    ports:
      - "8081:80"
    env_file: .env
    depends_on:
      - auth-service
      - user-service
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

