services:
  auth-service:
    image: auth-service:latest
    build: ./auth-service
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    secrets:
      - DB_PASSWORD
      - SECRET_KEY
    ports:
      - "5001:5000"
    networks:
      - micro-net
    deploy:
      replicas: 2

  user-service:
    image: user-service:latest
    build: ./user-service
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
    secrets:
      - DB_PASSWORD
      - SECRET_KEY
    ports:
      - "5002:5000"
    networks:
      - micro-net
    deploy:
      replicas: 2

  frontend:
    image: frontend:latest
    build: ./frontend
    depends_on:
      - auth-service
      - user-service
    ports:
      - "8081:80"
    networks:
      - micro-net
    deploy:
      replicas: 2

secrets:
  DB_PASSWORD:
    external: true
  SECRET_KEY:
    external: true

networks:
  micro-net:

