services:
  auth-service:
    image: chvald27/cdb-3324-term-project-auth-service:latest
    ports:
      - "5001:5000"
    networks:
      - micro-net
    env_file:
      - .env
    secrets:
      - db_password
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  user-service:
    image: chvald27/cdb-3324-term-project-user-service:latest
    ports:
      - "5002:5000"
    networks:
      - micro-net
    env_file:
      - .env
    secrets:
      - db_password
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: chvald27/cdb-3324-term-project-frontend:latest
    ports:
      - "8081:80"
    networks:
      - micro-net
    env_file:
      - .env
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

secrets:
  db_password:
    file: ./db_password.txt

networks:
  micro-net:
    driver: overlay
