{{- if .Values.authService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservices.fullname" . }}-auth
  labels:
    app: auth-service
    {{- include "microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.authService.service.type }}
  selector:
    app: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.authService.service.port }}
      targetPort: {{ .Values.authService.containerPort }}
{{- end }}

