apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices.fullname" . }}-secrets
  labels:
    {{- include "microservices.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_PASSWORD: "{{ .Values.global.db.password }}"
  SECRET_KEY: "{{ .Values.global.secretKey }}"

