apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: {{ .Values.images.user }}
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: DB_NAME
              value: {{ .Values.postgres.db | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
          ports:
            - containerPort: 5000

