apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-conf
  namespace: microservices
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      # Serve static files
      root /usr/share/nginx/html;
      index index.html;

      # Static content and SPA fallback
      location / {
        try_files $uri $uri/ /index.html;
      }

      # Proxy API requests to auth-service
      location /api/auth/ {
        proxy_pass http://auth-service:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
      }

      # Proxy API requests to user-service
      location /api/user/ {
        proxy_pass http://user-service:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
      }
    }

